# Generated by Django 3.2.9 on 2022-09-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0020_alter_transaction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmetamask',
            name='user',
        ),
    ]
