# Generated by Django 3.2.9 on 2022-09-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w3', '0021_remove_accountmetamask_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipfs',
            name='account',
        ),
        migrations.RemoveField(
            model_name='ipfs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.DeleteModel(
            name='AccountMetamask',
        ),
        migrations.DeleteModel(
            name='IPFS',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
